version: "3.7"
services:
  nginx:
    image: 10.128.2.130:5000/nginx:latest
    init: true
    #command: sleep 3600
    volumes:
      - type: volume
        source: nginx-logs
        target: /var/log/nginx
        volume:
          nocopy: true
    secrets:
      - source: nginx-crt
        target: /cert/nginx.pem
        uid: "500"
      - source: nginx-key
        target: /cert/nginx.key
        uid: "500"
    networks:
      - myweb
    configs:
      - source: nginx-config1
        target: /etc/nginx/nginx.conf
      - source: nginx-config2
        target: /etc/nginx/conf.d/default.conf
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 50M
    dns: 114.114.114.114
    ports:
      - target: 443
        published: 443
        protocol: tcp
    extra_hosts:
      - "web:10.128.2.103"
  web:
    image: 10.128.2.130:5000/tomcat:latest
    init: true
    volumes:
      - type: volume
        source: upload
        target: /opt/tomcat/upload
        volume:
          nocopy: true
    networks:
      - myweb
    configs:
      - source: nginx-config1
        target: /opt/tomcat/bin/setenv.sh
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '1'
          memory: 50M
    dns: 114.114.114.114
    ports:
      - target: 8080
        published: 80
        protocol: tcp
  redis:
    image: 10.128.2.130:5000/redis:0412
    init: true
    volumes:
      - type: volume
        source: redis_data
        target: /opt/redis/data
        volume:
          nocopy: true
      - type: volume
        source: redis_logs
        target: /opt/redis/logs
        volume:
          nocopy: true
    configs:
      - source: redis_config
        target: /opt/redis/conf/redis.conf
        uid: '500'
        gid: '500'
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: 1024M
    dns: 114.114.114.114
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
    networks:
      - myweb
  mysql:
    image: 10.128.2.130:5000/mysql:latest
    init: true
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql
        volume:
          nocopy: true
    networks:
      - myweb
    configs:
      - source: mysql_config
        target: /etc/my.cnf
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.name == db1
      resources:
        limits:
          cpus: '1'
          memory: 50M
    dns: 114.114.114.114
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
configs:
  nginx_config1:
    file: ./nginx.conf
  nginx_config2:
    file: ./default.conf
secrets:
  nginx-crt:
    file: ./2050666_www.jiangjunm.cn.pem
  nginx-key:
    file: ./2050666_www.jiangjunm.cn.key
volumes:
  nginx_logs:
  nfs_data:
    driver: local
    drive_opts:
      type: "nfs"
      o: "addr=10.128.1.130,rw"
      device: ":/data"

networks:
  myweb:
