version: '3'
services:
  mysql:
    image: mysql:8
    container_name: db_${project_name}
    init: true
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${mysql_root_password}
      MYSQL_DATABASE: ${mysql_db_name}
      MYSQL_USER: ${mysql_user}
      MYSQL_PASSWORD: ${mysql_password}
      TZ: Asia/Shanghai
    volumes:
      - ./my.cnf:/etc/my.cnf
      - /data/db_${project_name}:/var/lib/mysql
    ports:
      - ${mysql_mapping_port}:3306
    deploy:
      resources:
        limits:
          cpus: ${cpus}
          memory: ${memory}
    ulimits:
      nproc: 65536
      nofile: 65536
    networks:
      - mynet

networks:
  mynet:
